spring:
  application:
    name: prometheus-actuator
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

  metrics:
    tags:
      application: ${spring.application.name}